### ISSUE TITLE
Royalmail extension buy

### ISSUE THREAD

**Issue by sweetycoderkube** [meanbee/magento2-royalmail#19]
Hello,

Can you please provide the link we can buy meanbee royalmail extension ?

Thanks in advance.

**Comment by bobbyshaw** [comment]
This extension isn't available commercially. It's provided open-source as-is, without warranty only.

**Comment by sweetycoderkube** [comment]
can you please provide full code?

Thanks in advance.

**Comment by bobbyshaw** [comment]
This is the full code. We use composer for dependencies, so once you install you will pull in our php royal mail pricing library automatically https://github.com/meanbee/royalmail-php-library
