### ISSUE TITLE
Cant install  - version cant find issue

### ISSUE THREAD

**Issue by shyam100379** [meanbee/magento2-royalmail#21]
I am trying to install module using composer.
composer require "meanbee/module-royalmail"

But it says : [InvalidArgumentException]                                                                                                                                           
  Could not find a matching version of package meanbee/module-royalmail

Please advise. I have also tried to load module in app/code using the src folder. Still no luck.

Please advise. Thanks in advance.

**Comment by bobbyshaw** [comment]
This extension is non-functional and no longer supported. There is already an open issue that it's not installable through composer (#12) so I'm closing this one.
