### ISSUE TITLE
Tare weight of packaging

### ISSUE THREAD

**Issue by scathappens** [meanbee/magento2-royalmail#22]
Sorry if this is in the wrong place but i am not sure where i can ask questions

with this extention can you add a tare weight for your packaging?

our items are very small and light, thus is we weight them and set the item weight in magento for postage calculation then the weight of the packaging will probably push it over cost thresh holds. 

to solve this we need to be able to apply a standard tare weight per order/package that will be applied per package not per item.

also royal mail has a 2KG limit on international deliveries, if this does not also apply parcelforce worldwide shipping options will it split the order into multiple 2KG parcels?

appoligies again if i am asking this 'question' in the wrong place, if there is another place for me to put it then please let me know and i will place it there.

**Comment by bobbyshaw** [comment]
Hi @scathappens. I'm sorry to say that this module hasn't been updated in many years and is no longer supported. 

I don't believe it has the ability to specify a tare weight. 

It doesn't do any splitting of packages.
